### ISSUE TITLE
kadm api breakage

### ISSUE THREAD

**Issue by twmb** [zsmartex/pkg#19]
Hello,

I'm changing (and finalizing) some APIs in the kadm package, and using Github code search, I see this repo uses some APIs that I'm changing.

This line:
https://github.com/zsmartex/pkg/blob/7df73ff9fea3743965358c98d5587b321639fad3/services/kafka.go#L37
must change to either `Offsets().KOffsets()`, or just `KOffsets()`. I am not going to change any other API that this repo is currently using, sorry for the breakage -- I'm getting the kadm package ready for 1.0 stabilization and have always wanted to fix the awkward `.Into` functions.

Thanks!

**Comment by twmb** [comment]
(kadm is now 1.0 stable and the API will not change)

**Comment by huuhait** [comment]
Hi @twmb I'll update it to 1.0

Thanks you so much
